### ISSUE TITLE
The input field in the size is too small to see the value

### ISSUE THREAD

**Issue by mochi-sann** [premieroctet/openchakra#127]
<img width="292" alt="screenshot 2021-05-11 14 40 27" src="https://user-images.githubusercontent.com/44772513/117764175-075f6500-b267-11eb-814a-4b7a2a3e71cd.png">
As you can see in the image, even if you enter the height in the size input field of the component, you cannot see the value you entered because the width of the input field is very narrow.

**Comment by PierreCrb** [comment]
Hello ! This bug has been fixed in the PR https://github.com/premieroctet/openchakra/pull/139 ✅ 

Thank you!
