### ISSUE TITLE
feature request: Double click to edit text

### ISSUE THREAD

**Issue by codebender828** [premieroctet/openchakra#43]
Hi @PierreCrb !

Great work with OpenChakra! Love it.

One challenge I just noticed was that I'm unable to edit text in components when I double click the text.

Would be an interesting feature to add. I know this can be done by editing the text field on the right hand side panel. But would be even better to edit directly on the canvas.

![image](https://user-images.githubusercontent.com/21237954/74323463-804fe280-4dc0-11ea-9ec5-13bce5625bca.png)

**Comment by shinework** [comment]
Is online! Thanks to the release [v1.0.1](https://github.com/premieroctet/openchakra/releases/tag/v1.0.1) 🖖

**Comment by codebender828** [comment]
Great! Thanks!
