### ISSUE TITLE
Feature Request: Hovering children highlights them in the builder

### ISSUE THREAD

**Issue by timkindberg** [premieroctet/openchakra#49]
If I hover over one of the children in the right panel I'd like to see it highlight the component in the builder.

![image](https://user-images.githubusercontent.com/168046/74357713-4a920600-4d8e-11ea-9503-86b367bb1371.png)

**Comment by shinework** [comment]
Also done in the release [v1.0.1](https://github.com/premieroctet/openchakra/releases/tag/v1.0.1) 🖖
