### ISSUE TITLE
Option to remove extra padding from elements even in design mode?

### ISSUE THREAD

**Issue by akx** [premieroctet/openchakra#52]
If you switch from design mode to previewing the result, you'll see a possibly entirely different result.

I understand the padding is there for grabbability reasons, but it would be nice to be able to disable it.

**Comment by TransmissionsDev** [comment]
You can still edit in preview mode.

**Comment by shinework** [comment]
Yes, as @TransmissionsDev said, you can still edit in preview mode :)
