### ISSUE TITLE
Switch from Block to Flex back to Block doesn't return to original layout

### ISSUE THREAD

**Issue by atifsyedali** [premieroctet/openchakra#54]
1. Open https://openchakra.app/?ref=producthunt
2. Select AvatarGroup
3. Switch Layout > Display to Flex
4. Switch Layout > Display back to Block

Expected: Returns back to how it was
Actual: Doesn't.

Also:
1. The code shows the extra Flex properties remain on the AvatarGroup.
2. Reproducible with any other Stack component as well.

**Comment by guilhermedeandrade** [comment]
I'd like to work on this. Do you have any idea on what may be causing this bug @tlenclos ?

**Comment by shinework** [comment]
It will be fixed with this PR https://github.com/premieroctet/openchakra/pull/57

It adds default props (like display flex) to the inspector form

**Comment by guilhermedeandrade** [comment]
Ok thanks! @shinework
