### ISSUE TITLE
Feature Request: Save Components to Sidebar

### ISSUE THREAD

**Issue by mattwoodnyc** [premieroctet/openchakra#64]
I'd love to be able to save a component or group of component to the sidebar as a preset

**Comment by shinework** [comment]
We are currently working on that 🖖

**Comment by francescoagati** [comment]
also the possibility of import and export layouts in json could be a nice idea. i have see that internally the layout is a json data structure

**Comment by shinework** [comment]
@francescoagati import/export feature has been shipped :)
