### ISSUE TITLE
Can you start a patreon or a way to sponsor this project?

### ISSUE THREAD

**Issue by TransmissionsDev** [premieroctet/openchakra#66]
Openchakra is amazing. It's allowed me to speed up my workflow by multiple orders of magnitude. I've even begun using this for my actual work, and have been loving it! 

However, I worry that this project may stop being mantianied or be forgot about, and to encourage and ensure its basic maintaining, **I would love to support this project on OpenCollective or sponsor it or something else.** 

_**Is there anyway you could start a way for us to donate to this amazing project?**_

**Comment by shinework** [comment]
Hi @TransmissionsDev, thanks for your support! Super enthusiast to see that OpenChakra is useful! I have just setup the sponsorship button ♥️

**Comment by TransmissionsDev** [comment]
@shinework Amazing! 

Question: If I become a backer, could I request a feature that is important for me?

**Comment by shinework** [comment]
You can create an issue :) If it’s fitting with our roadmap, we'll do our best to implement this feature!

**Comment by TransmissionsDev** [comment]
@shinework Fantastic, I'll work on setting up an OpenCollective account when I have the time (asap) and open that feature request!

**Comment by zxti** [comment]
@TransmissionsDev May I ask what project you use this for and how you use it? I'm curious about what your workflow looks like. Thanks!

**Comment by TransmissionsDev** [comment]
@zxti OpenChakra allows me to turn what used to be two steps (prototyping in Sketch or Similar, and building a just the UI first) into one, where I prototype and create responsive code in one step, then just split it up into React components, and add application logic.
