### ISSUE TITLE
Feature Request: Store custom props in side panel

### ISSUE THREAD

**Issue by TransmissionsDev** [premieroctet/openchakra#67]
Sometimes I want to inject custom props into a component, however, the current system of the single box that doesn't show current custom props, only lets you add them, is difficult to use and hard to work with for a large project. 

Could we do something like this, where we could see all of our custom props and have two text boxes for each prop:
![demo image](https://i.imgur.com/G5q0flG.png)

❤️

**Comment by shinework** [comment]
@TransmissionsDev I have just created the PR for this feature, you can try the custom props panel here https://deploy-preview-68--openchakra.netlify.com/

Let me know your thoughts 🙂

**Comment by TransmissionsDev** [comment]
Hey @shinework! This looks great!

One thought is that next to each custom prop in the list, you could have an edit that would type that prop's name into the prop menu when clicked and move the user's keyboard foucs to the input (for easy updating).

This might work better if the prop name and value were in separate boxes, but are both viable and good options!

![](https://i.imgur.com/WxPUtjn.png)

Thank you for your quick (and high quality) work! 😄 

(I'm sending over $50 via Open Collective asap)

**Comment by shinework** [comment]
Thanks a lot for your donation 🙌
The edit button is up! https://deploy-preview-68--openchakra.netlify.com/

**Comment by TransmissionsDev** [comment]
> Thanks a lot for your donation 🙌
> The edit button is up! https://deploy-preview-68--openchakra.netlify.com/

Amazing!

**Comment by TransmissionsDev** [comment]
@shinework I have noticed that there is some glitchy behavior with this feature. 

When clicking on a Stack with some properties set by the width + height text boxes, and looking at the Custom Props panel, and then adding a Custom Prop, **non custom props, some with empty values show up!**

Here's the local storage component tree for reproduction: https://pastebin.com/MFdt5tku

Here's a picture describing my error: ![repro pic](https://i.imgur.com/QUrYXci.png)
