### ISSUE TITLE
Bug Report: Custom Props shows props that are not custom or not set!

### ISSUE THREAD

**Issue by TransmissionsDev** [premieroctet/openchakra#72]
When clicking on a Stack with some properties set by the width + height text boxes, and looking at the Custom Props panel, and then adding a Custom Prop, **non custom props, some with empty values show up!**

Here's the local storage component tree for reproduction: https://pastebin.com/MFdt5tku

Here's a picture describing my error: ![repro pic](https://i.imgur.com/QUrYXci.png)

**Comment by shinework** [comment]
Thanks for the report @TransmissionsDev, can you try this sandbox https://deploy-preview-73--openchakra.netlify.com ? The issue should be fixed :)

**Comment by TransmissionsDev** [comment]
@shinework Appears to work! Wasn't able to reproduce with the onboarding components. 😄

**Comment by TransmissionsDev** [comment]
@shinework I have just re-tested the newest deploy preview (73), but found that the custom props panel refuses to show the "rounded" prop even if it has been set via custom props? 

Can you look into this?
