### ISSUE TITLE
Bug: BackgroundColor showing as a custom prop

### ISSUE THREAD

**Issue by TransmissionsDev** [premieroctet/openchakra#77]
Very self explanatory, but backgroundColor is showing up as a custom prop for some reason. You can reproduce this with the onboarding components. 

![Repro Image](https://i.imgur.com/naJqJtP.jpg)

**Comment by TransmissionsDev** [comment]
@shinework Can you take a look at this?

**Comment by TransmissionsDev** [comment]
@shinework Please can we get this fixed already? Or can you link me to a file where I could make a pull request for this myself?

**Comment by shinework** [comment]
@TransmissionsDev bug fixed 😉
