### ISSUE TITLE
Feature request: Support for breakpoints and responsive styles

### ISSUE THREAD

**Issue by efossvold** [premieroctet/openchakra#79]
Thank you for creating this amazing app first of all, great work.

Any plans on supporting breaking points and [responsive styles](https://chakra-ui.com/responsive-styles), so that we'd be able to configure, and also see, how the components would look on various devices?

**Comment by shinework** [comment]
Thanks for your issue!
We plan to add buttons to quickly switch between the different viewports. Concerning responsive styles, this is not our priority, it would add a lot of complexity, but we will think about it :)
