### ISSUE TITLE
Duplicate Min H and Min W

### ISSUE THREAD

**Issue by hichana** [premieroctet/openchakra#81]
In the UI it shows a duplicate 'Min H' and 'Min W', but I believe one should be 'Max H' and 'Max W', right?

<img width="238" alt="Screen Shot 2020-03-28 at 3 12 35 PM" src="https://user-images.githubusercontent.com/8943047/77816552-dd9cba80-7106-11ea-9fbb-68ac971be2d6.png">

**Comment by shinework** [comment]
Thanks! It's fixed

**Comment by hichana** [comment]
@shinework openchakra is really helpful, thank you :)
