### ISSUE TITLE
v1 or v0.x support?

### ISSUE THREAD

**Issue by sw-yx** [premieroctet/openchakra#99]
Hi folks! great project!

just wanted to suggest that you could be clear about whether or not you support the upcoming 1.0 version or not. 

thank you!

**Comment by TransmissionsDev** [comment]
While I'm not a maintainer of the project, I am a long time supporter so I've been watching the project for a while.

v1 support is already WIP in a PR: https://github.com/premieroctet/openchakra/pulls

**Comment by sw-yx** [comment]
ah OK! I looked thru the issues but didn't see a PR

**Comment by shinework** [comment]
Hey @sw-yx, like @TransmissionsDev said, the v1 will be land soon (you can already try it here https://deploy-preview-91--openchakra.netlify.app but there are still few bugs)

And yes we need to find a way to support both versions, I think the main domain https://openchakra.app will handle the new v1 version as soon as it's published, and a subdomain (smth like https://v0.openchakra.app) will handle the v0
